owner: reearth
repo: status

sites:
  - name: Re:Earth Classic
    url: $REEARTH_CLASSIC_WEB_URL
  - name: Re:Earth Classic API
    url: $REEARTH_CLASSIC_API_URL
  - name: Re:Earth CMS
    url: $REEARTH_CMS_WEB_URL
    headers:
      - "Authorization: Bearer $REEARTH_CMS_BEARER_TOKEN"
  - name: Re:Earth CMS API
    url: $REEARTH_CMS_API_URL
    headers:
      - "Authorization: Bearer $REEARTH_CMS_BEARER_TOKEN"
  - name: Re:Earth Visualizer
    url: $REEARTH_VISUALIZER_WEB_URL
    headers:
      - "Authorization: Bearer $REEARTH_VISUALIZER_BEARER_TOKEN"
  - name: Re:Earth Visualizer API
    url: $REEARTH_VISUALIZER_API_URL
    headers:
      - "Authorization: Bearer $REEARTH_VISUALIZER_BEARER_TOKEN"

status-website:
  cname: status.reearth.io
  faviconSvg: https://reearth.io/img/logo.svg
  logoUrl: https://reearth.io/img/logo.svg
  name: Re:Earth Status Page
  introTitle: "**Re:Earth** - A free, open, highly extensible WebGIS platform"
  introMessage: This is the status page for Re:Earth, a free, open, highly extensible WebGIS platform.
  navbar:
    - title: Homepage
      href: https://reearth.io
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
