owner: reearth
repo: status

sites:
  - name: Re:Earth Classic
    url: $REEARTH_CLASSIC_API_URL
  - name: Re:Earth CMS
    url: $REEARTH_CMS_API_URL
  - name: Re:Earth Visualizer
    url: $REEARTH_VISUALIZER_API_URL

status-website:
  cname: status.reearth.io
  faviconSvg: https://reearth.io/img/logo.svg
  logoUrl: https://reearth.io/img/logo.svg
  name: Re:Earth Status Page
  introTitle: "**Re:Earth** - A free, open, highly extensible WebGIS platform"
  introMessage: This is the status page for Re:Earth, a free, open, highly extensible WebGIS platform.
  navbar:
    - title: Homepage
      href: https://reearth.io
    - title: Status
      href: /

commitMessages:
  commitAuthorName: "reearth-app[bot]"
  commitAuthorEmail: "909148+reearth-app[bot]@users.noreply.github.com"

user-agent: reearth-app[bot]
