name: Set GitHub App Token  
on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:
jobs:
  release:
    name: Generate GH_PAT secret
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write
    steps:
      - name: Generate an app token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GH_PAT || github.token }}
      - name: Update GH_PAT secret
        env:
          APP_TOKEN: ${{ steps.generate-token.outputs.token }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "$APP_TOKEN" | gh secret set GH_PAT \
            --repo ${{ github.repository }} \
            --app actions \
            --body -
